### ISSUE TITLE
When using <Distube>.play() with nicovideo.jp link, it have some distube error

### ISSUE THREAD

**Issue by RainyXeon** [distubejs/yt-dlp#5]
**When I use `<Distube>.play()` with `nicovideo.jp` link, I have this URL error maybe from yt-dlp and distube:**
```
06-10-2023 09:53:11 - ERROR       - DisTubeError [INVALID_TYPE]: Expected 'an URL', but got 'niconico_dmc:sm42833545/archive_h264_360p/archive_aac_64kbps' (string)
{
  level: 'error',
  message: DisTubeError [INVALID_TYPE]: Expected 'an URL', but got 'niconico_dmc:sm42833545/archive_h264_360p/archive_aac_64kbps' (string)
      at Function.DirectLink (D:\Github\AzurDream\node_modules\distube\src\core\DisTubeStream.ts:56:13)
      at _QueueManager.createStream (D:\Github\AzurDream\node_modules\distube\src\core\manager\QueueManager.ts:171:26)
      at _QueueManager.playSong (D:\Github\AzurDream\node_modules\distube\src\core\manager\QueueManager.ts:193:27)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _QueueManager.create (D:\Github\AzurDream\node_modules\distube\src\core\manager\QueueManager.ts:39:19)
      at async _DisTubeHandler.playSong (D:\Github\AzurDream\node_modules\distube\src\core\DisTubeHandler.ts:340:24)
      at async _DisTube.play (D:\Github\AzurDream\node_modules\distube\src\DisTube.ts:210:9) {
    errorCode: 'INVALID_TYPE'
  },
  timestamp: '06-10-2023 09:53:11'
}
```
Maybe is from yt-dlp or distube?

**Further information:**

- Plugin version: 1.1.3
- DisTube version: 4.0.5
- discord.js version: 14.13.0
- Node.js version: 20.6.0
- Operating system: Windows 11 x64

**Comment by skick1234** [comment]
This is due to yt-dlp not returning the correct stream url for this provider I guess. I will check it later.
